apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # Contexto de seguridad a nivel de Pod
      securityContext:
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.fsGroup }}
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
      containers:
        - name: nextjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          # Contexto de seguridad a nivel de contenedor
          securityContext:
            readOnlyRootFilesystem: {{ .Values.security.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.security.allowPrivilegeEscalation }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          # Liveness probe asegura que el contenedor se reinicie si el proceso de Node crashea
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          # Readiness probe evita enviar tráfico hasta que Next.js esté listo para servir peticiones
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            # Requerido por Next.js para escribir en .next/cache en tiempo de ejecución
            - mountPath: /app/.next/cache
              name: next-cache
            # Requerido por el sistema base Alpine/Node para archivos temporales del SO
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        # Volúmenes efímeros mapeados a la memoria/disco del nodo esclavo
        - name: next-cache
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}