apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.fsGroup }}
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
      containers:
        - name: nextjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            readOnlyRootFilesystem: {{ .Values.security.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.security.allowPrivilegeEscalation }}
          
          # Inyección de variables de entorno en tiempo de ejecución (Runtime)
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecrets.name }}
                  key: {{ .Values.externalSecrets.key }}
          
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/.next/cache
              name: next-cache
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: next-cache
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}